defaultAssertionDataset: mh4l_ga4_assertion
defaultLocation: australia-southeast1
defaultProject: my-health-429206
vars:
  GA4_DATASET: analytics_362574079
  LOCAL_TIMEZONE: Australia/Sydney
  QUALITY_DATASET: mh4l_ga4_quality
  TRANSFORMATIONS_DATASET: mh4l_ga4_transformations
  OUTPUTS_DATASET: mh4l_ga4_outputs
